name: Simple App CD
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/simple-app
          tags: ${{ github.sha }}, latest  

      #- name: Deploy para meu host
      #  uses: easingthemes/ssh-deploy@main
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #    ARGS: "-rlgoDzvc -i --delete"
      #    SOURCE: "./"
      #    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #    REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #    TARGET: ${{ secrets.REMOTE_TARGET }}
         
      
      - name: Docker stopping process
        run: |
          docker stop simple-app || echo "Container was not running" 

      - name: Docker pull process 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-app:latest

      - name: Docker start application process
        run: | 
          docker run --name simple-app -p 8080:8080 $(docker images --filter=reference='igfurlan/simple-app:latest' --format "{{.ID}}") &